// GETTERS
export const DOUBLE_COUNTER = 'DOUBLE_COUNTER'
export const STRING_COUNTER = 'STRING_COUNTER'

//MUTATIONS
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

//ACTIONS
export const INCREMENT_ACTION = 'INCREMENT_ACTION'
export const DECREMENT_ACTION = 'DECREMENT_ACTION'
